M48
; DRILL file {KiCad 9.0.0} date 2025-04-26T19:09:06+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-26T19:09:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X83.82Y-109.474
X83.82Y-139.7
X127.0Y-139.7
T2
X86.36Y-104.14
X86.36Y-144.78
X124.46Y-144.78
M30
