M48
; DRILL file {KiCad 9.0.0} date 2025-04-27T22:02:36+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-27T22:02:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.3Y-4.0
X3.3Y-5.8
X5.0Y-4.0
X5.0Y-5.8
T2
X3.425Y-4.125
X3.425Y-5.675
X4.875Y-5.675
M30
